services:
  migrate_command:
    class: Helmich\Namespacify\MigrateCommand
    calls:
      - [setFileLocator, ["@file_locator"]]
      - [setNamespaceConverter, ["@namespace_converter_astbased"]]
#  backport_command:
#    class: Helmich\Namespacify\BackportCommand
#    calls:
#      - [setFileLocator, ["@file_locator"]]
#      - [setNamespaceConverter, ["@namespace_converter_backward"]]
  file_locator:
    class: Helmich\Namespacify\File\FileLocator
  namespace_converter_astbased:
    class: Helmich\Namespacify\Converter\ASTBasedNamespaceConverter
    arguments: ["@php_parser"]
  namespace_converter_forward:
    class: Helmich\Namespacify\Converter\ForwardNamespaceConverter
  namespace_converter_backward:
    class: Helmich\Namespacify\Converter\BackwardNamespaceConverter
    arguments: ["@php_parser"]
  php_parser:
    class: 'PhpParser\Parser'
    arguments: ["@php_lexer"]
  php_lexer:
    class: 'PhpParser\Lexer'